#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Ruby ------
if [[ -d "$HOME/.rbenv/bin" ]]; then
  eval "$(rbenv init -)"
fi

# autosuggestion doesn't yet work with zprezto; that's really a shame.
# set up autocomplete
#source ~/.zsh-autosuggestions/autosuggestions.zsh

# Enable autosuggestions automatically
# this is now in editor/init.sh
#zle-line-init() {
#    zle autosuggest-start
#}

#bindkey '^T' autosuggest-toggle
#bindkey '^f' vi-forward-blank-word
#bindkey '^F' vi-forward-word

# some command-line aliases that apply across machines
alias cds="cd ~/src; pwd"
alias ec="emacsclient -n -c "

# source in any local aliases
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

